<template>
  <PageContainer>
    <a-spin :spinning="loading">
      <div class="context-banner"><HomeOutlined /><span>{{ t('rooms.form.hotel') }}</span><strong>{{ selectedHotelName || '-' }}</strong></div>
      <div class="form-breadcrumb"><a-button type="text" @click="goBack"><LeftOutlined />{{ t('rooms.title') }}</a-button><RightOutlined /><strong>{{ isEdit ? t('rooms.form.editTitle') : t('rooms.form.createTitle') }}</strong></div>
      <div class="merchant-page-header"><h1>{{ isEdit ? t('rooms.form.editTitle') : t('rooms.form.createTitle') }}</h1><p>{{ t('rooms.form.subtitle', { hotel: selectedHotelName || '-' }) }}</p></div>
      <a-alert v-if="latestRevision?.status === 3" type="error" show-icon :message="t('rooms.review.rejected')" :description="latestRevision.reject_reason" class="review-alert" />
      <a-form layout="vertical" class="room-form-grid">
        <section class="proto-card"><h2>{{ t('rooms.sections.information') }}</h2><div class="two-grid"><a-form-item :label="t('rooms.form.hotel')" required><a-select v-model:value="form.goodsId" :disabled="isEdit"><a-select-option v-for="hotel in hotels" :key="hotel.id" :value="hotel.id">{{ hotel.goods_name }}</a-select-option></a-select></a-form-item><a-form-item :label="t('rooms.fields.roomName')" required><a-input v-model:value="form.roomName" :maxlength="100" :placeholder="t('rooms.placeholders.roomName')" /></a-form-item><a-form-item :label="t('rooms.fields.roomCode')"><a-input v-model:value="form.roomCode" :maxlength="50" :placeholder="t('rooms.placeholders.roomCode')" /></a-form-item><a-form-item class="span-2" :label="t('rooms.fields.description')"><a-textarea v-model:value="form.description" :maxlength="400" show-count :rows="4" :placeholder="t('rooms.placeholders.description')" /></a-form-item></div></section>
        <section class="proto-card"><h2>{{ t('rooms.sections.capacity') }}</h2><div class="three-grid"><a-form-item :label="t('rooms.fields.maxAdults')" required><a-input-number v-model:value="form.maxAdults" :min="1" class="full" /></a-form-item><a-form-item :label="t('rooms.fields.maxChildren')"><a-input-number v-model:value="form.maxChildren" :min="0" class="full" /></a-form-item><a-form-item :label="t('rooms.fields.maxGuests')" required><a-input-number v-model:value="form.maxGuests" :min="1" class="full" /></a-form-item></div></section>
        <section class="proto-card"><h2>{{ t('rooms.sections.configuration') }}</h2><div class="three-grid"><a-form-item :label="t('rooms.fields.bedType')" required><a-select v-model:value="form.bedType" :options="bedTypes.map(value => ({ value, label: value }))" /></a-form-item><a-form-item :label="t('rooms.fields.bedCount')"><a-input-number v-model:value="form.bedCount" :min="1" class="full" /></a-form-item><a-form-item :label="t('rooms.fields.area')" required><a-input v-model:value="form.area" :placeholder="t('rooms.placeholders.area')" /></a-form-item><a-form-item :label="t('rooms.fields.floorName')"><a-input v-model:value="form.floorName" :placeholder="t('rooms.placeholders.floor')" /></a-form-item><a-form-item :label="t('rooms.fields.roomView')"><a-select v-model:value="form.roomView" :options="roomViews.map(value => ({ value, label: value }))" allow-clear /></a-form-item><a-form-item :label="t('rooms.fields.smoking')"><a-radio-group v-model:value="form.smoking"><a-radio :value="0">{{ t('rooms.fields.noSmoking') }}</a-radio><a-radio :value="1">{{ t('rooms.fields.smokingAllowed') }}</a-radio></a-radio-group></a-form-item></div></section>
        <section class="proto-card"><h2>{{ t('rooms.sections.facilities') }}</h2><p>{{ t('rooms.sections.facilitiesDesc') }}</p><div class="facility-picker"><button v-for="item in facilityOptions" :key="item" type="button" :class="{ active: form.facilities.includes(item) }" @click="toggleFacility(item)"><CheckOutlined v-if="form.facilities.includes(item)" />{{ item }}</button></div><small>{{ t('rooms.form.facilitiesSelected', { count: form.facilities.length }) }}</small></section>
        <section class="proto-card"><h2>{{ t('rooms.sections.media') }}</h2><p>{{ t('rooms.media.rules') }}</p><div class="media-grid"><div v-for="(url, index) in form.images" :key="url" class="media-item" :class="{ cover: index === 0 }"><img :src="url" :alt="`room-${index + 1}`" /><span v-if="index === 0">{{ t('rooms.media.cover') }}</span><div><a-button size="small" type="text" @click="makeCover(index)">{{ t('rooms.media.setCover') }}</a-button><a-button size="small" type="text" danger @click="removeImage(index)"><DeleteOutlined /></a-button></div></div><button v-if="form.images.length < 10" type="button" class="upload-slot" @click="imageInput?.click()"><CameraOutlined /><span>{{ t('rooms.media.uploadPhotos') }}</span></button></div><input ref="imageInput" hidden type="file" accept="image/jpeg,image/png,image/webp" multiple @change="uploadImages" />
          <div class="video-row"><video v-if="form.videoUrl" :src="form.videoUrl" controls /><button v-else type="button" class="video-upload" @click="videoInput?.click()"><VideoCameraOutlined />{{ t('rooms.media.uploadVideo') }}</button><a-button v-if="form.videoUrl" danger @click="form.videoUrl = ''">{{ t('common.delete') }}</a-button></div><input ref="videoInput" hidden type="file" accept="video/mp4,video/quicktime" @change="uploadVideo" />
        </section>
        <section class="proto-card"><h2>{{ t('rooms.sections.pricing') }}</h2><div class="three-grid"><a-form-item :label="t('rooms.fields.currency')"><a-select v-model:value="form.currency" :options="currencies" /></a-form-item><a-form-item :label="t('rooms.fields.basePrice')" required><a-input-number v-model:value="form.basePrice" :min="0" :precision="2" class="full" /></a-form-item><a-form-item :label="t('rooms.fields.weekendPrice')"><a-input-number v-model:value="form.weekendPrice" :min="0" :precision="2" class="full" /></a-form-item><a-form-item :label="t('rooms.fields.extraBedPrice')"><a-input-number v-model:value="form.extraBedPrice" :min="0" :precision="2" class="full" /></a-form-item></div></section>
        <section class="proto-card"><h2>{{ t('rooms.sections.inventory') }}</h2><div class="two-grid"><a-form-item :label="t('rooms.fields.baseStock')" required><a-input-number v-model:value="form.baseStock" :min="0" class="full" /></a-form-item><a-form-item :label="t('rooms.fields.launchStock')"><a-input-number v-model:value="form.launchStock" :min="0" :max="form.baseStock" class="full" /></a-form-item></div><div class="workflow"><div v-for="(step, index) in workflowSteps" :key="step.label" :class="{ active: workflowIndex === index }"><span>{{ index + 1 }}</span><strong>{{ step.label }}</strong><small>{{ step.desc }}</small></div></div></section>
        <section class="proto-card"><h2>{{ t('rooms.sections.policies') }}</h2><div class="two-grid"><a-form-item :label="t('rooms.fields.cancellationPolicy')"><a-select v-model:value="form.cancellationPolicy" :options="cancellationPolicies.map(value => ({ value, label: value }))" /></a-form-item><a-form-item :label="t('rooms.fields.mealPlan')"><a-select v-model:value="form.mealPlan" :options="mealPlans.map(value => ({ value, label: value }))" /></a-form-item><a-form-item class="span-2" :label="t('rooms.fields.checkinNotes')"><a-textarea v-model:value="form.checkinNotes" :rows="3" :maxlength="500" /></a-form-item></div></section>
      </a-form>
      <div class="sticky-footer"><a-button @click="goBack">{{ t('common.cancel') }}</a-button><a-space><a-button :loading="saving" @click="save(false)"><FileTextOutlined />{{ t('rooms.actions.saveDraft') }}</a-button><a-button type="primary" :loading="saving" @click="save(true)">{{ t('rooms.actions.submitReview') }}<ArrowRightOutlined /></a-button></a-space></div>
    </a-spin>
  </PageContainer>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { message } from 'ant-design-vue';
import { useI18n } from 'vue-i18n';
import { ArrowRightOutlined, CameraOutlined, CheckOutlined, DeleteOutlined, FileTextOutlined, HomeOutlined, LeftOutlined, RightOutlined, VideoCameraOutlined } from '@ant-design/icons-vue';
import PageContainer from '@/components/PageContainer.vue';
import { apiRoomDetail, apiRoomHotels, apiRoomSave, apiRoomUpload, type RoomHotelOption, type RoomRevision } from '@/api/rooms';

const route = useRoute(); const router = useRouter(); const { t } = useI18n(); const loading = ref(false); const saving = ref(false); const hotels = ref<RoomHotelOption[]>([]); const latestRevision = ref<RoomRevision | null>(null); const imageInput = ref<HTMLInputElement>(); const videoInput = ref<HTMLInputElement>();
const roomId = computed(() => Number(route.params.id || 0)); const isEdit = computed(() => roomId.value > 0);
const emptyForm = () => ({ goodsId: Number(route.query.goodsId || 0) || undefined as number | undefined, roomName: '', roomCode: '', description: '', bedType: '', bedCount: 1, area: '', maxAdults: 2, maxChildren: 1, maxGuests: 3, floorName: '', roomView: '', smoking: 0, breakfast: 0, mealPlan: '', cancellationPolicy: '', checkinNotes: '', currency: 'THB', basePrice: 0, weekendPrice: 0, extraBedPrice: 0, baseStock: 0, launchStock: 0, images: [] as string[], videoUrl: '', facilities: ['WiFi', 'Air Conditioning', 'TV'], status: 1, sort: 0 });
const form = reactive(emptyForm());
const selectedHotelName = computed(() => hotels.value.find(item => item.id === form.goodsId)?.goods_name || '');
const bedTypes = ['1 King Bed', '1 Queen Bed', '2 Single Beds', '1 King + Sofa Bed', '2 Double Beds', 'Bunk Beds']; const roomViews = ['Ocean View', 'City View', 'Garden View', 'Pool View', 'Mountain View', 'No Specific View']; const facilityOptions = ['WiFi', 'Air Conditioning', 'TV', 'Mini Bar', 'Safe', 'Balcony', 'Bathtub', 'Kitchenette', 'Pool Access', 'Coffee Machine', 'Hair Dryer', 'Blackout Curtains']; const currencies = ['THB', 'USD', 'SGD', 'EUR'].map(value => ({ value, label: value }));
const mealPlans = computed(() => [t('rooms.meal.roomOnly'), t('rooms.meal.breakfast'), t('rooms.meal.halfBoard'), t('rooms.meal.fullBoard'), t('rooms.meal.allInclusive')]); const cancellationPolicies = computed(() => [t('rooms.cancelPolicy.free48'), t('rooms.cancelPolicy.nonRefundable'), t('rooms.cancelPolicy.free7'), t('rooms.cancelPolicy.flexible')]); const workflowSteps = computed(() => [{ label: t('rooms.workflow.draft'), desc: t('rooms.workflow.draftDesc') }, { label: t('rooms.workflow.review'), desc: t('rooms.workflow.reviewDesc') }, { label: t('rooms.workflow.published'), desc: t('rooms.workflow.publishedDesc') }]); const workflowIndex = computed(() => latestRevision.value?.status === 1 ? 1 : latestRevision.value?.status === 2 ? 2 : 0);
function assign(row: Record<string, unknown>) { Object.assign(form, { goodsId: Number(row.goods_id || form.goodsId), roomName: String(row.room_name || ''), roomCode: String(row.room_code || ''), description: String(row.description || ''), bedType: String(row.bed_type || ''), bedCount: Number(row.bed_count || 1), area: String(row.area || ''), maxAdults: Number(row.max_adults || 2), maxChildren: Number(row.max_children || 0), maxGuests: Number(row.max_guests || 2), floorName: String(row.floor_name || ''), roomView: String(row.room_view || ''), smoking: Number(row.smoking || 0), breakfast: Number(row.breakfast || 0), mealPlan: String(row.meal_plan || ''), cancellationPolicy: String(row.cancellation_policy || ''), checkinNotes: String(row.checkin_notes || ''), currency: String(row.currency || 'THB'), basePrice: Number(row.base_price || 0), weekendPrice: Number(row.weekend_price || 0), extraBedPrice: Number(row.extra_bed_price || 0), baseStock: Number(row.base_stock || 0), launchStock: Number(row.launch_stock || 0), images: Array.isArray(row.images) ? row.images : [], videoUrl: String(row.video_url || ''), facilities: Array.isArray(row.facilities) ? row.facilities : [], status: Number(row.status || 1), sort: Number(row.sort || 0) }); }
function toggleFacility(item: string) { const index = form.facilities.indexOf(item); index >= 0 ? form.facilities.splice(index, 1) : form.facilities.push(item); } function makeCover(index: number) { const url = form.images.splice(index, 1)[0]; form.images.unshift(url); } function removeImage(index: number) { form.images.splice(index, 1); } function goBack() { void router.push('/rooms'); }
async function imageSize(file: File) { return new Promise<{ width: number; height: number }>((resolve, reject) => { const image = new Image(); image.onload = () => { URL.revokeObjectURL(image.src); resolve({ width: image.width, height: image.height }); }; image.onerror = reject; image.src = URL.createObjectURL(file); }); }
async function uploadImages(event: Event) { const input = event.target as HTMLInputElement; const files = Array.from(input.files || []).slice(0, 10 - form.images.length); for (const file of files) { if (file.size > 10 * 1024 * 1024) { message.warning(t('rooms.media.imageTooLarge')); continue; } const size = await imageSize(file); if (size.width < 800 || size.height < 600) { message.warning(t('rooms.media.imageTooSmall')); continue; } const result = await apiRoomUpload(file, 'image'); form.images.push(result.url); } input.value = ''; }
async function videoDuration(file: File) { return new Promise<number>((resolve, reject) => { const video = document.createElement('video'); video.onloadedmetadata = () => { URL.revokeObjectURL(video.src); resolve(video.duration); }; video.onerror = reject; video.src = URL.createObjectURL(file); }); }
async function uploadVideo(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; if (file.size > 500 * 1024 * 1024 || await videoDuration(file) > 300) { message.warning(t('rooms.media.videoInvalid')); input.value = ''; return; } const result = await apiRoomUpload(file, 'video'); form.videoUrl = result.url; input.value = ''; }
function validate(submit: boolean) { if (!form.goodsId || !form.roomName.trim() || !form.bedType || !form.area || form.maxGuests < form.maxAdults || form.launchStock > form.baseStock) { message.warning(t('rooms.form.requiredTip')); return false; } if (submit && form.images.length === 0) { message.warning(t('rooms.media.photoRequired')); return false; } return true; }
async function save(submit: boolean) { if (!validate(submit)) return; saving.value = true; try { const result = await apiRoomSave({ id: roomId.value || undefined, ...form, publishStatus: submit ? 1 : 0 }); message.success(submit ? t('rooms.messages.submitted') : t('rooms.messages.draftSaved')); await router.replace(`/rooms/${result.id}`); } finally { saving.value = false; } }
onMounted(async () => { loading.value = true; try { hotels.value = await apiRoomHotels(); if (!form.goodsId && hotels.value.length) form.goodsId = hotels.value[0].id; if (isEdit.value) { const detail = await apiRoomDetail(roomId.value); latestRevision.value = detail.latestRevision; if (detail.latestRevision?.status === 1) { message.warning(t('rooms.messages.pendingLocked')); await router.replace(`/rooms/${roomId.value}`); return; } assign(detail.editable as Record<string, unknown>); } } finally { loading.value = false; } });
</script>

<style scoped lang="less">
.context-banner{display:flex;align-items:center;gap:9px;padding:10px 14px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc;color:#64748b}.context-banner strong{color:#0f172a}.form-breadcrumb{display:flex;align-items:center;gap:4px;margin:12px 0;color:#64748b}.merchant-page-header{margin-bottom:16px}.merchant-page-header h1{margin:0;font-size:22px;color:#0f172a}.merchant-page-header p{margin:4px 0 0;color:#64748b}.review-alert{margin-bottom:16px}.room-form-grid{display:grid;gap:14px;padding-bottom:84px}.proto-card{padding:20px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.proto-card h2{font-size:15px;margin:0 0 15px;color:#0f172a}.proto-card>p{margin:-8px 0 14px;color:#64748b;font-size:12px}.two-grid,.three-grid{display:grid;gap:0 16px}.two-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.three-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.span-2{grid-column:1/-1}.full{width:100%}.facility-picker{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:10px}.facility-picker button{padding:7px 12px;border:1px solid #dbe3ec;border-radius:8px;background:#fff;color:#475569}.facility-picker button.active{border-color:#2563eb;background:#eff6ff;color:#1d4ed8}.media-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.media-item,.upload-slot{height:116px;border:1px dashed #cbd5e1;border-radius:10px;position:relative;overflow:hidden;background:#f8fafc}.media-item img{width:100%;height:100%;object-fit:cover}.media-item>span{position:absolute;top:7px;left:7px;padding:2px 6px;border-radius:4px;background:#2563eb;color:#fff;font-size:10px}.media-item>div{position:absolute;right:4px;bottom:4px;display:flex;border-radius:5px;background:rgba(255,255,255,.92)}.media-item.cover{border:2px solid #2563eb}.upload-slot{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;color:#64748b}.video-row{display:flex;align-items:center;gap:12px;margin-top:14px}.video-row video{width:240px;max-height:150px;border-radius:8px}.video-upload{height:90px;width:240px;border:1px dashed #cbd5e1;border-radius:9px;background:#f8fafc;color:#64748b}.workflow{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.workflow>div{padding:12px;border:1px solid #e2e8f0;border-radius:9px}.workflow>div.active{border-color:#2563eb;background:#eff6ff}.workflow span{display:inline-flex;width:22px;height:22px;align-items:center;justify-content:center;border-radius:50%;background:#e2e8f0;margin-right:7px}.workflow strong{font-size:12px}.workflow small{display:block;margin:7px 0 0 29px;color:#64748b}.sticky-footer{position:fixed;left:var(--sidebar-width,220px);right:0;bottom:0;z-index:10;display:flex;justify-content:space-between;padding:13px 24px;border-top:1px solid #e2e8f0;background:#fff;box-shadow:0 -8px 24px rgba(15,23,42,.05)}@media(max-width:900px){.two-grid,.three-grid{grid-template-columns:1fr}.media-grid{grid-template-columns:repeat(2,1fr)}.sticky-footer{left:0}}
</style>
