import { get, post } from '@/utils/http';
import type { PageData } from '@/api/types';
type Row = Record<string, any>;
export const complianceCategories = ['Booking', 'Listing', 'Operations', 'Pricing', 'Reviews', 'Finance', 'Compliance', 'Marketing'];
export const apiRules = (params: Record<string, unknown>): Promise<PageData<Row>> => get('/admin/compliance/rule/list', params);
export const apiRuleHistory = (params: Record<string, unknown>): Promise<PageData<Row>> => get('/admin/compliance/rule/history', params);
export const apiRuleSave = (data: Record<string, unknown>): Promise<Row> => post('/admin/compliance/rule/save', data);
export const apiRulePublish = (data: Record<string, unknown>): Promise<Row> => post('/admin/compliance/rule/publish', data);
export const apiViolations = (params: Record<string, unknown>): Promise<PageData<Row>> => get('/admin/compliance/violation/list', params);
export const apiViolationRecord = (data: Record<string, unknown>): Promise<Row> => post('/admin/compliance/violation/record', data);
export const apiViolationHandle = (data: Record<string, unknown>): Promise<Row> => post('/admin/compliance/violation/handle', data);
export const apiWarnings = (params: Record<string, unknown>): Promise<PageData<Row>> => get('/admin/compliance/warning/list', params);
export const apiWarningIssue = (data: Record<string, unknown>): Promise<Row> => post('/admin/compliance/warning/issue', data);
export const apiWarningRevoke = (data: Record<string, unknown>): Promise<Row> => post('/admin/compliance/warning/revoke', data);
export const apiComplianceHistory = (params: Record<string, unknown>): Promise<PageData<Row>> => get('/admin/compliance/history/list', params);
