-- ============================================================
-- 业务表 05:订单(文档 5.2.2 + 业务模块5:订单/退款/核销)
-- 库:mtrip_business
-- 分表策略:order_main 按 created_at 月份分表(order_main_YYYYMM),
--   本文件为模板表,定时任务每月末预建下月分表
-- ============================================================
USE `mtrip_business`;

-- 订单主表(严格按文档 5.2.2,月分表模板)
CREATE TABLE IF NOT EXISTS `order_main` (
  `id`                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no`            VARCHAR(32)  NOT NULL COMMENT '订单号(唯一)',
  `site_id`             BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属站点ID',
  `user_id`             BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  `order_type`          TINYINT      NOT NULL DEFAULT 1 COMMENT '订单类型:1酒店 2门票',
  `merchant_id`         BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商户ID',
  `supplier_id`         BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '供应商ID',
  `goods_id`            BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商品ID',
  `goods_name`          VARCHAR(200) NOT NULL COMMENT '商品名称',
  `goods_image`         VARCHAR(255) NOT NULL DEFAULT '' COMMENT '商品图片',
  `sku_id`              BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '房型/票种ID',
  `sku_name`            VARCHAR(100) NOT NULL COMMENT '规格名称(房型/票种)',
  `quantity`            INT          NOT NULL DEFAULT 1 COMMENT '购买数量',
  `unit_price`          DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '单价',
  `original_price`      DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '原价',
  `total_amount`        DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '订单总金额',
  `discount_amount`     DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '优惠金额',
  `coupon_id`           BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '优惠券ID',
  `coupon_discount`     DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '优惠券抵扣',
  `points_discount`     DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '积分抵扣',
  `pay_amount`          DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '实付金额',
  `platform_commission` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '平台佣金',
  `merchant_receivable` DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '商户实收',
  `supplier_cost`       DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '供应商成本',
  `pay_method`          TINYINT      NOT NULL DEFAULT 0 COMMENT '支付方式:1Stripe 2PayPal',
  `pay_trade_no`        VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '支付流水号',
  `pay_time`            DATETIME     NULL DEFAULT NULL COMMENT '支付时间',
  `order_status`        TINYINT      NOT NULL DEFAULT 0 COMMENT '订单状态:0待支付 1已支付 2已入住/已核销 3已完成 4已取消 5退款中 6已退款 7已过期',
  `refund_status`       TINYINT      NOT NULL DEFAULT 0 COMMENT '退款状态:0无 1申请中 2部分退款 3全额退款',
  `use_date`            DATE         NULL DEFAULT NULL COMMENT '使用/入住日期',
  `end_date`            DATE         NULL DEFAULT NULL COMMENT '离店/过期日期',
  `contact_name`        VARCHAR(50)  NOT NULL COMMENT '联系人姓名',
  `contact_phone`       VARCHAR(255) NOT NULL COMMENT '联系人手机号(加密)',
  `verify_code`         VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '核销码',
  `cancel_reason`       VARCHAR(500) NOT NULL DEFAULT '' COMMENT '取消原因',
  `cancel_time`         DATETIME     NULL DEFAULT NULL COMMENT '取消时间',
  `remark`              VARCHAR(500) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at`          DATETIME     NULL DEFAULT NULL COMMENT '删除时间(软删)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_site_id` (`site_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_pay_time` (`pay_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单主表(月分表模板 order_main_YYYYMM)';

-- 退款单表
CREATE TABLE IF NOT EXISTS `order_refund` (
  `id`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `refund_no`      VARCHAR(32)  NOT NULL COMMENT '退款单号(唯一)',
  `site_id`        BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属站点ID',
  `order_id`       BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  `order_no`       VARCHAR(32)  NOT NULL COMMENT '订单号',
  `user_id`        BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  `merchant_id`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商户ID',
  `refund_type`    TINYINT      NOT NULL DEFAULT 1 COMMENT '退款类型:1全额 2部分',
  `apply_amount`   DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '申请退款金额',
  `refund_amount`  DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '实际退款金额',
  `deduct_amount`  DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '退改扣费金额',
  `reason`         VARCHAR(500) NOT NULL DEFAULT '' COMMENT '退款原因',
  `images`         JSON         NULL COMMENT '凭证图片',
  `status`         TINYINT      NOT NULL DEFAULT 0 COMMENT '状态:0待商户审核 1待平台审核 2退款中 3已退款 4已驳回 5已撤销',
  `merchant_audit_by`   BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '商户审核人',
  `merchant_audit_time` DATETIME NULL DEFAULT NULL COMMENT '商户审核时间',
  `platform_audit_by`   BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '平台审核人',
  `platform_audit_time` DATETIME NULL DEFAULT NULL COMMENT '平台审核时间',
  `audit_remark`   VARCHAR(500) NOT NULL DEFAULT '' COMMENT '审核备注/驳回原因',
  `refund_trade_no` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '第三方退款流水号',
  `refund_time`    DATETIME     NULL DEFAULT NULL COMMENT '退款到账时间',
  `created_at`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `updated_at`     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at`     DATETIME     NULL DEFAULT NULL COMMENT '删除时间(软删)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_no` (`refund_no`),
  KEY `idx_site_id` (`site_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款单表';

-- 核销日志表(永久留存审计,不可删除)
CREATE TABLE IF NOT EXISTS `order_verify_log` (
  `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `site_id`       BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属站点ID',
  `order_id`      BIGINT UNSIGNED NOT NULL COMMENT '订单ID',
  `order_no`      VARCHAR(32)  NOT NULL COMMENT '订单号',
  `verify_code`   VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '核销码',
  `merchant_id`   BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '商户ID',
  `device_id`     BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '核销设备ID,0=后台手工核销',
  `operator_id`   BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作员ID',
  `operator_name` VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '操作员姓名',
  `verify_type`   TINYINT      NOT NULL DEFAULT 1 COMMENT '核销方式:1扫码 2输码 3后台手工',
  `status`        TINYINT      NOT NULL DEFAULT 1 COMMENT '核销状态:1成功 2失败 3已撤销',
  `fail_reason`   VARCHAR(255) NOT NULL DEFAULT '' COMMENT '失败原因',
  `revoke_reason` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '撤销原因(撤销需审批)',
  `revoke_by`     BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '撤销审批人',
  `created_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '核销时间',
  PRIMARY KEY (`id`),
  KEY `idx_site_id` (`site_id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='核销日志表(永久留存,不可删除)';
