-- ============================================================
-- 清理本脚本生成的测试数据
-- 只删除测试保留 ID 段内的行(商户/用户等 >=1001,系统配置类 >=101),
-- 不会触碰 database/seed/ 下的种子数据(菜单、角色、KYC 模板、站点等)。
-- ============================================================
SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

USE `mtrip_business`;

DELETE FROM `affiliate_application` WHERE id >= 1001;
DELETE FROM `affiliate_code` WHERE id >= 1001;
DELETE FROM `affiliate_commission_log` WHERE id >= 1001;
DELETE FROM `affiliate_fraud_flag` WHERE id >= 1001;
DELETE FROM `affiliate_partner` WHERE id >= 1001;
DELETE FROM `affiliate_program` WHERE id >= 1001;
DELETE FROM `affiliate_withdraw` WHERE id >= 1001;
DELETE FROM `chat_conversation` WHERE id >= 1001;
DELETE FROM `chat_message` WHERE id >= 1001;
DELETE FROM `compliance_history` WHERE id >= 1001;
DELETE FROM `finance_account_entry` WHERE id >= 1001;
DELETE FROM `finance_flow` WHERE id >= 1001;
DELETE FROM `finance_merchant_settle` WHERE id >= 1001;
DELETE FROM `finance_tax_config` WHERE id >= 1001;
DELETE FROM `finance_withdraw` WHERE id >= 1001;
DELETE FROM `goods_category` WHERE id >= 1001;
DELETE FROM `goods_daily_stock` WHERE id >= 1000001;
DELETE FROM `goods_info` WHERE id >= 1001;
DELETE FROM `goods_refund_rule` WHERE id >= 1001;
DELETE FROM `goods_review` WHERE id >= 1001;
DELETE FROM `goods_stock_log` WHERE id >= 1001;
DELETE FROM `hotel_room_type` WHERE id >= 1001;
DELETE FROM `marketing_activity` WHERE id >= 1001;
DELETE FROM `marketing_activity_goods` WHERE id >= 1001;
DELETE FROM `marketing_banner` WHERE id >= 1001;
DELETE FROM `marketing_campaign` WHERE id >= 1001;
DELETE FROM `marketing_coupon` WHERE id >= 1001;
DELETE FROM `marketing_coupon_receive` WHERE id >= 1001;
DELETE FROM `marketing_longstay_tier` WHERE id >= 1001;
DELETE FROM `marketing_points_rule` WHERE id >= 1001;
DELETE FROM `marketing_promo_code` WHERE id >= 1001;
DELETE FROM `marketing_voucher` WHERE id >= 1001;
DELETE FROM `marketing_welcome_reward` WHERE id >= 1001;
DELETE FROM `merchant_access_code_log` WHERE id >= 1001;
DELETE FROM `merchant_account` WHERE id >= 3001;
DELETE FROM `merchant_activity_log` WHERE id >= 1001;
DELETE FROM `merchant_admin` WHERE id >= 4001;
DELETE FROM `merchant_admin_role` WHERE admin_id >= 4001;
DELETE FROM `merchant_application` WHERE id >= 1001;
DELETE FROM `merchant_application_business` WHERE id >= 2001;
DELETE FROM `merchant_application_note` WHERE id >= 3004;
DELETE FROM `merchant_blacklist` WHERE id >= 1001;
DELETE FROM `merchant_document_event` WHERE id >= 1001;
DELETE FROM `merchant_group` WHERE id >= 1001;
DELETE FROM `merchant_impersonation_session` WHERE id >= 1001;
DELETE FROM `merchant_info` WHERE id >= 1001;
DELETE FROM `merchant_notify` WHERE id >= 1001;
DELETE FROM `merchant_notify_delivery` WHERE notify_id >= 1001;
DELETE FROM `merchant_notify_read` WHERE notify_id >= 1001;
DELETE FROM `merchant_property_history` WHERE id >= 1001;
DELETE FROM `merchant_status_history` WHERE merchant_id >= 1001;
DELETE FROM `merchant_store` WHERE id >= 2001;
DELETE FROM `merchant_verify_document` WHERE id >= 1001;
DELETE FROM `merchant_verify_document_revision` WHERE id >= 1032;
DELETE FROM `merchant_verify_timeline` WHERE id >= 1001;
DELETE FROM `merchant_violation` WHERE id >= 1001;
DELETE FROM `merchant_warning` WHERE id >= 1001;
DELETE FROM `notify_record` WHERE id >= 1001;
DELETE FROM `order_main` WHERE id >= 1001;
DELETE FROM `order_refund` WHERE id >= 1001;
DELETE FROM `order_trip` WHERE id >= 1001;
DELETE FROM `order_verify_log` WHERE id >= 1001;
DELETE FROM `platform_rule` WHERE id >= 1001;
DELETE FROM `platform_rule_revision` WHERE id >= 1002;
DELETE FROM `ranking_destination` WHERE id >= 1001;
DELETE FROM `ranking_history` WHERE id >= 1001;
DELETE FROM `ranking_listing` WHERE id >= 1001;
DELETE FROM `ranking_market` WHERE id >= 1001;
DELETE FROM `supplier_admin` WHERE id >= 1001;
DELETE FROM `supplier_admin_role` WHERE admin_id >= 1001;
DELETE FROM `supplier_goods` WHERE id >= 1001;
DELETE FROM `supplier_info` WHERE id >= 1001;
DELETE FROM `supplier_settle` WHERE id >= 1001;
DELETE FROM `ticket_type` WHERE id >= 1001;
DELETE FROM `user_action_log` WHERE id >= 1001;
DELETE FROM `user_appeal` WHERE id >= 1001;
DELETE FROM `user_balance_log` WHERE id >= 1001;
DELETE FROM `user_blacklist` WHERE id >= 1001;
DELETE FROM `user_favorite` WHERE id >= 1001;
DELETE FROM `user_feedback` WHERE id >= 1001;
DELETE FROM `user_fraud` WHERE id >= 1001;
DELETE FROM `user_info` WHERE id >= 1001;
DELETE FROM `user_member_level` WHERE id >= 1001;
DELETE FROM `user_points_log` WHERE id >= 1001;
DELETE FROM `user_referral` WHERE id >= 1001;
DELETE FROM `user_traveler` WHERE id >= 1001;
DELETE FROM `verify_device` WHERE id >= 1001;
DELETE FROM `verify_rule` WHERE id >= 1001;
USE `mtrip_system`;

DELETE FROM `app_theme` WHERE id >= 101;
DELETE FROM `help_announcement` WHERE id >= 1001;
DELETE FROM `help_article` WHERE id >= 1001;
DELETE FROM `help_category` WHERE id >= 1001;
DELETE FROM `help_search_log` WHERE id >= 1001;
DELETE FROM `sys_admin` WHERE id >= 101;
DELETE FROM `sys_admin_login_log` WHERE id >= 1001;
DELETE FROM `sys_admin_role` WHERE admin_id >= 101;
DELETE FROM `sys_api_access_log` WHERE id >= 1001;
DELETE FROM `sys_client` WHERE id >= 101;
DELETE FROM `sys_client_perm_template` WHERE id >= 101;
DELETE FROM `sys_feature_flag` WHERE id >= 101;
DELETE FROM `sys_file` WHERE id >= 1001;
DELETE FROM `sys_map_config` WHERE id >= 101;
DELETE FROM `sys_operation_log` WHERE id >= 1001;
DELETE FROM `sys_pay_channel` WHERE id >= 101;
DELETE FROM `sys_role` WHERE id >= 101;
DELETE FROM `sys_role_menu` WHERE role_id >= 101;
DELETE FROM `sys_site_config` WHERE id >= 101;
DELETE FROM `sys_sms_channel` WHERE id >= 101;
DELETE FROM `sys_sms_template` WHERE id >= 101;
DELETE FROM `sys_storage` WHERE id >= 101;

SET FOREIGN_KEY_CHECKS = 1;
