<template>
  <div class="snapshot">
    <div class="room-title"><div><h2>{{ room.room_name }}</h2><p>{{ room.description }}</p></div><strong>{{ room.currency }} {{ Number(room.base_price || 0).toLocaleString() }} <small>/ {{ tr('night', '晚') }}</small></strong></div>
    <a-image-preview-group><div class="gallery"><a-image v-for="(url, i) in room.images || []" :key="url" :src="url" :alt="room.room_name" :class="{ hero: i === 0 }" /></div></a-image-preview-group>
    <section><h3>{{ tr('Room Specifications', '客房规格') }}</h3><div class="specs"><div v-for="[label, value] in specs" :key="label"><span>{{ label }}</span><strong>{{ value }}</strong></div></div></section>
    <section><h3>{{ tr('Room Amenities', '客房设施') }}</h3><div class="amenities"><span v-for="item in room.facilities || []" :key="item"><WifiOutlined v-if="item === 'wifi' || item === 'WiFi'" /><CheckCircleOutlined v-else />{{ amenityLabels[item] ? tr(...amenityLabels[item]!) : item }}</span></div></section>
    <section v-if="room.video_url"><h3>{{ tr('Room Video', '客房视频') }}</h3><video :src="room.video_url" controls preload="metadata" /></section>
    <section v-if="room.panorama?.enabled && room.panorama.url"><h3>{{ tr('360° Room View', '360° 客房全景') }}</h3><RoomPanorama :src="room.panorama.url" :hint="tr('Drag to look around · Scroll to zoom', '拖动查看全景，滚动缩放')" :error-text="tr('Panorama could not be loaded', '全景加载失败')" /></section>
    <section v-if="room.vr_tour?.url"><h3>{{ tr('VR Tour', 'VR 导览') }}</h3><a-image v-if="room.vr_tour.cover" :src="room.vr_tour.cover" :width="240" /><p>{{ tr('External VR provider is not connected.', '外部 VR 服务商尚未接入。') }}</p><p class="url">{{ room.vr_tour.url }}</p></section>
    <section v-if="room.floor_plan?.enabled && room.floor_plan.image"><h3>{{ tr('3D Floor Plan', '交互平面图') }}</h3><p>{{ tr('Select a pin to explore the room.', '点击定位点查看客房细节。') }}</p><RoomFloorPlan :image="room.floor_plan.image" :hotspots="room.floor_plan.hotspots || []" :label="tr('Room floor plan', '客房平面图')" /></section>
    <section><h3>{{ tr('Policies & Additional Information', '政策及补充信息') }}</h3><div class="specs"><div><span>{{ t('rooms.fields.mealPlan') }}</span><strong>{{ mealLabel }}</strong></div><div><span>{{ t('rooms.fields.weekendPrice') }}</span><strong>{{ room.currency }} {{ room.weekend_price || room.base_price }}</strong></div><div><span>{{ t('rooms.fields.extraBedPrice') }}</span><strong>{{ room.currency }} {{ room.extra_bed_price || 0 }}</strong></div><div><span>{{ t('rooms.fields.roomCode') }}</span><strong>{{ room.room_code || '-' }}</strong></div></div><p>{{ room.refund_policy ? policyLabel : room.cancellation_policy || '-' }}</p><ul v-if="room.refund_policy?.ruleType === 2"><li v-for="rule in room.refund_policy.rules" :key="rule.hours_before">{{ tr('At least', '至少提前') }} {{ rule.hours_before }} {{ tr('hours: refund', '小时：退还') }} {{ rule.refund_rate }}%</li></ul><p>{{ room.refund_policy?.remark }}</p><p>{{ room.checkin_notes }}</p></section>
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { CheckCircleOutlined, WifiOutlined } from '@ant-design/icons-vue';
import type { MerchantRoom } from '@/api/rooms';
import { amenityLabels, areaLabel, bedLabel, useRoomText } from '../presentation';
import RoomPanorama from './RoomPanorama.vue';
import RoomFloorPlan from './RoomFloorPlan.vue';
const props = defineProps<{ room: Partial<MerchantRoom> }>(); const tr = useRoomText(); const { t } = useI18n();
const specs = computed(() => [[tr('Max Guests', '最多入住人数'), String(props.room.max_guests || 0)], [tr('Room Size', '客房面积'), areaLabel(props.room)], [tr('Bedding Setup', '床型配置'), bedLabel(props.room)], [tr('Room Quantity', '客房总数'), String(props.room.base_stock || 0)], [tr('Default Sellable Quota', '默认可售配额'), String(props.room.launch_stock || 0)], [tr('Breakfast Included', '包含早餐'), Number(props.room.breakfast) > 0 ? tr('Yes', '是') : tr('No', '否')], [t('rooms.fields.floorName'), props.room.floor_name || '-'], [t('rooms.fields.roomView'), props.room.room_view || '-'], [t('rooms.fields.smoking'), Number(props.room.smoking) === 1 ? t('rooms.fields.smokingAllowed') : t('rooms.fields.noSmoking')]]);
const mealLabel = computed(() => ({ room_only: t('rooms.meal.roomOnly'), breakfast: t('rooms.meal.breakfast'), half_board: t('rooms.meal.halfBoard'), full_board: t('rooms.meal.fullBoard'), all_inclusive: t('rooms.meal.allInclusive') }[props.room.meal_plan || ''] || props.room.meal_plan || '-'));
const policyLabel = computed(() => props.room.refund_policy?.ruleType === 1 ? tr('Free cancellation', '免费取消') : props.room.refund_policy?.ruleType === 3 ? tr('Non-refundable', '不可退款') : tr('Tiered cancellation policy', '阶梯退款政策'));
</script>
<style scoped>
.room-title{display:flex;justify-content:space-between;gap:24px;align-items:center;margin-bottom:20px}.room-title h2{font-size:22px;margin:0}.room-title p{color:#868b99;white-space:pre-wrap}.room-title>strong{color:#4865ed;white-space:nowrap;font-size:20px}.room-title small{font-size:12px;font-weight:400;color:#9397a1}.gallery{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px;max-height:410px;overflow:auto}.gallery :deep(.ant-image-img){height:160px;object-fit:cover;border-radius:10px}.gallery .hero{grid-row:span 2}.gallery .hero :deep(img){height:332px}section{border-top:1px solid #e9ebf1;padding:22px 0}section h3{font-size:16px;margin:0 0 18px}.specs{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.specs span{display:block;font-size:12px;color:#9095a3;margin-bottom:6px}.specs strong{font-size:14px}.amenities{display:flex;gap:12px;flex-wrap:wrap}.amenities>span{display:flex;align-items:center;gap:8px;padding:10px 14px;background:#f6f7fb;border-radius:8px}.snapshot video{width:100%;max-height:400px;border-radius:10px}.url{word-break:break-all;color:#8a8f9c}@media(max-width:650px){.room-title{display:block}.gallery{grid-template-columns:1fr 1fr}.gallery .hero{grid-column:1/-1;grid-row:auto}.gallery .hero :deep(img){height:220px}.specs{grid-template-columns:1fr 1fr}}
</style>
